name: PR Checker
on:
  pull_request:
    types: [opened, reopened,synchronize]
jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action
        uses: actions/checkout@v3
      - name: Hello World
        run: echo "PR Created!"
      - name: Fetch PR Details
        uses: ./  # Refers to this action in the repository
